import Head from "next/head"
import { Title, createStyles, rem } from "@mantine/core"
import HeaderCarousel from "@/components/header-carousel"
import Search from "@/components/search"
import Services from "@/components/services"
import Clinics from "@/components/clinics"
import Articles from "@/components/articles"

const useStyles = createStyles((theme) => ({
    para: {
        fontWeight: 100,
        fontSize: rem(20),
        marginTop:100,
    },
}))

export default function Home() {
    const { classes } = useStyles()

    return (
        <>
            <Head>
                <title>SafeShe - The Women Safety App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

            {/* <Title className={classes.Title}>
                    {
                        "Safe She"
                    }
                </Title> */}
                <p className={classes.para}>
                    {
                        "No need of panicking at the time of emergency. We've got guaranteed women safety measures on our web app!"
                    }
                </p>


                <HeaderCarousel />

                <Search />

                <Services />

                <Clinics />

                <Articles />
            </main>
        </>
    )
}
